
name: Build
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: NPM Install
        run: npm install

      - uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Docker build and push
        env:
          DOCKER_CLI_ACI: 1
        run: |
          docker build -t myntra:latest .
          docker tag myntra:latest aliumair0/myntra:latest
          docker push aliumair0/myntra:latest 
      - name: Install Docker Scout
        run: |
         curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh | sh
         docker scout version

      - name: Docker Scout Scan
        run: |
         docker scout quickview aliumair0/myntra:latest
         docker scout cves aliumair0/myntra:latest
  deploy:
   needs: build
   runs-on: self-hosted
   steps:
     - name: Configure kubeconfig
       run: aws eks --region us-east-1 update-kubeconfig --name EKS_CLOUD

     - name: Deploy to EKS
       run: kubectl apply -f deployment-service.yml

     - name: Verify deployment
       run: |
        kubectl get pods
        kubectl get svc  
     
